name: Playwright Tests E2E Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # 💡 FORZAMOS EL ENTORNO A NODE.JS 24 PARA EVITAR DEPRECACIONES (BUENAS PRÁCTICAS 2026)
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    # 🚀 EL PASO FINAL: SINCRONIZACIÓN AUTOMÁTICA CON AWS S3 (OHIO)
    - name: Deploy Report to AWS S3
      if: ${{ !cancelled() }} # Se ejecuta siempre, incluso si fallan los tests, para poder auditar los errores en la web
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2' # Región de Ohio, donde creaste tu bucket
      run: |
        echo "Iniciando la transferencia del reporte a la infraestructura de AWS S3..."
        aws s3 sync playwright-report/ s3://fabian-playwright-qa --delete